// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdeq_aGBaGoj6PuScBfsXyFpWSojrgeOo',
    appId: '1:413447347609:android:f661a0557301eaa7808708',
    messagingSenderId: '413447347609',
    projectId: 'rinosat-app',
    storageBucket: 'rinosat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPOZw4hWdb3nO7LPEDbPkBaunNtqVeDW0',
    appId: '1:413447347609:ios:37b58fc4daa025a3808708',
    messagingSenderId: '413447347609',
    projectId: 'rinosat-app',
    storageBucket: 'rinosat-app.firebasestorage.app',
    iosClientId:
        '413447347609-h66476ar90h8v8m8hogdh2i586pbadvo.apps.googleusercontent.com',
    iosBundleId: 'com.rinosat.app',
  );
}
