// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdeq_aGBaGoj6PuScBfsXyFpWSojrgeOo',
    appId: '1:413447347609:android:f661a0557301eaa7808708',
    messagingSenderId: '413447347609',
    projectId: 'rinosat-app',
    storageBucket: 'rinosat-app.firebasestorage.app',
  );

  // TODO: pendente — não existe um app iOS "org.rinosatapp.manager" registado
  // no Firebase (o GoogleService-Info.plist enviado é do bundle com.rinosat.app,
  // que é de OUTRA app). Os valores abaixo são os antigos (placeholder) e
  // NÃO devem ser usados em produção até criares o app iOS certo na Firebase
  // console e me enviares o GoogleService-Info.plist correspondente.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa-dBF6DlD3CtKODjgrpoUjEwESsMttj8',
    appId: '1:847296525014:ios:a9ee9ddfdb62f027',
    messagingSenderId: '847296525014',
    projectId: 'rinosat-app',
    databaseURL: 'https://rinosat-app.firebaseio.com',
    storageBucket: 'rinosat-app.firebasestorage.app',
    iosClientId: '847296525014-8d6vg8a08lfk1mp8j6mbgv96gq3n7cob.apps.googleusercontent.com',
    iosBundleId: 'org.rinosatapp.manager',
  );

}